/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список платежей мерчанта
         * @description Возвращает платежи мерчанта из `X-Merchant-Id` — источник журнала песочницы. Сортировка — по `created_at` по убыванию (новые сверху). Пагинации нет. От повторных запросов создания с тем же ключом список не растёт.
         */
        get: operations["listPayments"];
        put?: never;
        /**
         * Создать платёж (идемпотентно)
         * @description Создаёт платёж. Заголовки `Idempotency-Key` и `X-Merchant-Id`
         *     обязательны.
         *
         *     Семантика повторов:
         *
         *     - **201** — платёж создан этим запросом (ключ встречен впервые);
         *     - **200** — повтор с тем же ключом и тем же телом вернул **существующий
         *       ресурс**, включая `id` и `created_at`; второй платёж не создан.
         *
         *     Статус созданного платежа определяется правилом тестовых сумм
         *     (см. описание API): `amount_minor % 100 == 1` → `failed`,
         *     `% 100 == 2` → `succeeded`, иначе `pending`. Суммы `1` и `2`
         *     минорных единицы — тоже триггеры правила.
         */
        post: operations["createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить платёж по id
         * @description Возвращает платёж мерчанта из `X-Merchant-Id`. Несуществующий платёж и платёж другого мерчанта неразличимы — оба дают 404 `payment_not_found`.
         */
        get: operations["getPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отменить платёж
         * @description Переводит платёж из `pending` в `canceled` и отвечает **200**.
         *
         *     Отмена **идемпотентна**: повторная отмена уже отменённого платежа —
         *     снова **200** и тот же результат. Отмена платежа в терминальном статусе
         *     `succeeded` или `failed` → **409** `payment_not_cancelable`.
         *     Тела у запроса нет.
         */
        post: operations["cancelPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Платёж — основной ресурс API. */
        Payment: {
            /**
             * @description Идентификатор платежа; выдаётся сервисом.
             * @example pay_7Jf3K9qT2mVb
             */
            id: string;
            /**
             * @description Статус платежа. `pending` — создан и ждёт; `succeeded` / `failed` — терминальные, задаются правилом тестовых сумм синхронно при создании; `canceled` — отменён из `pending`.
             * @enum {string}
             */
            status: "pending" | "succeeded" | "failed" | "canceled";
            /**
             * @description Причина статуса: `test_amount_rule`, если статус задан правилом тестовых сумм при создании, иначе `null`.
             * @enum {string|null}
             */
            status_reason: "test_amount_rule" | null;
            /**
             * @description Сумма в минорных единицах валюты (копейки, центы), целое строго больше нуля, не выше границы безопасного целого (2^53 − 1). Правило тестовых сумм: `amount_minor % 100 == 1` → `failed`, `% 100 == 2` → `succeeded`, иначе `pending`; суммы `1` и `2` — тоже триггеры.
             * @example 125000
             */
            amount_minor: number;
            /**
             * @description Код валюты из белого списка; регистр строгий.
             * @enum {string}
             */
            currency: "RUB" | "USD" | "EUR";
            /**
             * @description Идентификатор заказа на стороне мерчанта; непустая строка до 64 символов.
             * @example order-2026-0825-0001
             */
            order_id: string;
            /**
             * @description Описание платежа, до 512 символов; необязательно при создании — тогда `null`. Хранится и отдаётся **как есть**: сервер и клиенты не интерпретируют и не исполняют его содержимое.
             * @example Подписка на тариф «Про», август
             */
            description: string | null;
            /**
             * Format: date-time
             * @description Момент создания платежа, RFC 3339 (UTC). При повторе с тем же ключом возвращается исходное значение.
             * @example 2026-08-25T12:34:56.000Z
             */
            created_at: string;
        };
        /** @description Тело запроса на создание платежа. Поля сверх схемы запрещены (`additionalProperties: false`): неизвестное поле → 422 `validation_failed`. «Тем же телом» при повторе считается совпадение по разобранным полям, не по байтам. */
        PaymentCreateRequest: {
            /**
             * @description Сумма в минорных единицах валюты, целое строго больше нуля, не выше границы безопасного целого (2^53 − 1). Иначе — 422 `validation_failed`. Суммы с `amount_minor % 100 == 1` или `== 2` — триггеры правила тестовых сумм (включая суммы `1` и `2`).
             * @example 125000
             */
            amount_minor: number;
            /**
             * @description Код валюты; регистр строгий, иначе — 422 `validation_failed`.
             * @enum {string}
             */
            currency: "RUB" | "USD" | "EUR";
            /**
             * @description Идентификатор заказа мерчанта; непустая строка до 64 символов, иначе — 422 `validation_failed`.
             * @example order-2026-0825-0001
             */
            order_id: string;
            /**
             * @description Необязательное описание, до 512 символов, иначе — 422 `validation_failed`. Хранится и отдаётся как есть, не интерпретируется.
             * @example Подписка на тариф «Про», август
             */
            description?: string;
        };
        /** @description Список платежей мерчанта, новые сверху. */
        PaymentList: {
            /** @description Платежи, отсортированные по `created_at` по убыванию. */
            payments: components["schemas"]["Payment"][];
        };
        /**
         * @description Машиночитаемый код ошибки; полный перечень — в описании API.
         * @enum {string}
         */
        ErrorCode: "merchant_id_required" | "invalid_merchant_id" | "idempotency_key_required" | "invalid_idempotency_key" | "malformed_request" | "validation_failed" | "idempotency_key_reuse" | "request_in_progress" | "payment_not_found" | "payment_not_cancelable";
        /** @description Единый конверт ошибки. Для `validation_failed` в `details.errors` лежит карта «поле → описание нарушения». */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /**
                 * @description Человекочитаемое пояснение; текст не является контрактом.
                 * @example Заголовок X-Merchant-Id обязателен
                 */
                message: string;
                /** @description Необязательные дополнительные данные. Для `validation_failed` — объект `errors` с картой «поле → нарушение»; для `payment_not_cancelable` — текущий `status` платежа. */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Заголовок `X-Merchant-Id` отсутствует или невалиден. */
        MerchantHeaderError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Платёж не существует или принадлежит другому мерчанту — эти случаи неразличимы. */
        PaymentNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Идентификатор мерчанта; обязателен на всех запросах. Непустая строка до 64 символов из набора `A–Z a–z 0–9 . _ -`. Заголовок отсутствует → 400 `merchant_id_required`; значение невалидно → 400 `invalid_merchant_id`. Ключи идемпотентности и видимость платежей скоупятся по мерчанту. */
        XMerchantId: string;
        /** @description Ключ идемпотентности создания платежа; обязателен. Непустая строка от 1 до 255 символов, формат не навязывается — песочница генерирует UUID. Пустое значение приравнивается к отсутствию заголовка → 400 `idempotency_key_required`; длиннее 255 символов → 400 `invalid_idempotency_key`. Ключ действует ограниченное время — **TTL, по умолчанию 24 часа**: в этом окне повтор с тем же телом возвращает 200 и тот же ресурс, повтор с другим телом — 409 `idempotency_key_reuse`; после истечения TTL тот же ключ создаёт новый платёж. Ключ уникален в пределах мерчанта. */
        IdempotencyKey: string;
        /** @description Идентификатор платежа, выданный сервисом при создании. */
        PaymentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPayments: {
        parameters: {
            query?: never;
            header: {
                /** @description Идентификатор мерчанта; обязателен на всех запросах. Непустая строка до 64 символов из набора `A–Z a–z 0–9 . _ -`. Заголовок отсутствует → 400 `merchant_id_required`; значение невалидно → 400 `invalid_merchant_id`. Ключи идемпотентности и видимость платежей скоупятся по мерчанту. */
                "X-Merchant-Id": components["parameters"]["XMerchantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Платежи мерчанта, новые сверху. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentList"];
                };
            };
            400: components["responses"]["MerchantHeaderError"];
        };
    };
    createPayment: {
        parameters: {
            query?: never;
            header: {
                /** @description Идентификатор мерчанта; обязателен на всех запросах. Непустая строка до 64 символов из набора `A–Z a–z 0–9 . _ -`. Заголовок отсутствует → 400 `merchant_id_required`; значение невалидно → 400 `invalid_merchant_id`. Ключи идемпотентности и видимость платежей скоупятся по мерчанту. */
                "X-Merchant-Id": components["parameters"]["XMerchantId"];
                /** @description Ключ идемпотентности создания платежа; обязателен. Непустая строка от 1 до 255 символов, формат не навязывается — песочница генерирует UUID. Пустое значение приравнивается к отсутствию заголовка → 400 `idempotency_key_required`; длиннее 255 символов → 400 `invalid_idempotency_key`. Ключ действует ограниченное время — **TTL, по умолчанию 24 часа**: в этом окне повтор с тем же телом возвращает 200 и тот же ресурс, повтор с другим телом — 409 `idempotency_key_reuse`; после истечения TTL тот же ключ создаёт новый платёж. Ключ уникален в пределах мерчанта. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreateRequest"];
            };
        };
        responses: {
            /** @description Повтор с тем же ключом и тем же телом: возвращён существующий ресурс — тот же `id`, тот же `created_at`. Второй платёж не создан. Именно по паре статусов 201/200 песочница отличает «новый платёж» от «тот же платёж». */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            /** @description Платёж создан: ключ идемпотентности встречен впервые. Статус — по правилу тестовых сумм. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            /** @description Отсутствует или невалиден обязательный заголовок, либо тело не разобрано как JSON-объект. Порядок проверок: `X-Merchant-Id` → `Idempotency-Key` → разбор тела; ответ — первый непройденный слой. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Конфликт ключа идемпотентности: тот же ключ с другим телом, либо первый запрос с этим ключом ещё обрабатывается. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Тело запроса разобрано, но поля не прошли проверку: `amount_minor`, `currency`, `order_id`, `description` или поле сверх схемы. Карта нарушений — в `details.errors`: ключ — имя поля, значение — описание нарушения; перечисляются все нарушения разом. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPayment: {
        parameters: {
            query?: never;
            header: {
                /** @description Идентификатор мерчанта; обязателен на всех запросах. Непустая строка до 64 символов из набора `A–Z a–z 0–9 . _ -`. Заголовок отсутствует → 400 `merchant_id_required`; значение невалидно → 400 `invalid_merchant_id`. Ключи идемпотентности и видимость платежей скоупятся по мерчанту. */
                "X-Merchant-Id": components["parameters"]["XMerchantId"];
            };
            path: {
                /** @description Идентификатор платежа, выданный сервисом при создании. */
                id: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Платёж найден. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            400: components["responses"]["MerchantHeaderError"];
            404: components["responses"]["PaymentNotFound"];
        };
    };
    cancelPayment: {
        parameters: {
            query?: never;
            header: {
                /** @description Идентификатор мерчанта; обязателен на всех запросах. Непустая строка до 64 символов из набора `A–Z a–z 0–9 . _ -`. Заголовок отсутствует → 400 `merchant_id_required`; значение невалидно → 400 `invalid_merchant_id`. Ключи идемпотентности и видимость платежей скоупятся по мерчанту. */
                "X-Merchant-Id": components["parameters"]["XMerchantId"];
            };
            path: {
                /** @description Идентификатор платежа, выданный сервисом при создании. */
                id: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Платёж отменён — либо этим запросом, либо ранее (повторная отмена возвращает тот же результат). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            400: components["responses"]["MerchantHeaderError"];
            404: components["responses"]["PaymentNotFound"];
            /** @description Платёж в терминальном статусе, отмена невозможна. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
